# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_auto_20170612_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default=b'', upload_to=b''),
        ),
    ]
